"""add new attribute to the meal

Revision ID: c2ae04e624d8
Revises: fe8977dccfe6
Create Date: 2026-05-22 09:54:04.296029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ae04e624d8'
down_revision = 'fe8977dccfe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('staple', 'protein', 'snack', name='menu_item_type', native_enum=False), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
